version: '3.3'

services:

  mariadb:
    image: mariadb:latest
    volumes:
      - ./data/mariadb-data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: !!!YOUR_PASSWD_HERE
      MARIADB_DATABASE: redmine
    restart: always

  redmine:
    image: redmine:latest
    ports:
      - 82:3000
    volumes:
      - ./data/redmine-plugins:/usr/src/redmine/plugins
      - ./data/redmine-themes:/usr/src/redmine/public/themes
      - ./data/redmine-data:/usr/src/redmine/files
    environment:
      REDMINE_DB_MYSQL: mariadb
      REDMINE_DB_PASSWORD: !!!YOUR_PASSWD_HERE
      REDMINE_DB_DATABASE: redmine
    restart: always